In [88]:
import numpy as np

# Policy Iteration 
Policy iteration means getting an optimal policy by improving the basic policy by iteratively evaluating the state value function for each state.
It has two part 

1- policy evaluation:- In this we evaluate value function of each action in a state by using the policy.

2- Policy improvement:- Iteratively evaluating state value function for each state to get the optimal policy.

In [89]:
#Initialize the parameters
gamma = 1
rewardSize = -1
gridSize = 4
terminationStates = [[0, 0], [gridSize -1, gridSize -1]]
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]] 
numIterations = 1000

In [90]:
def actionRewardFunction(initialPosition, action):
    if initialPosition in terminationStates:
        return initialPosition, 0
    
    reward = rewardSize
    finalPosition = np.array(initialPosition) + np.array(action)
    
    
    if -1 in finalPosition or 4 in finalPosition:
        finalPosition = initialPosition
        
    return finalPosition, reward

In [91]:
gridWorld = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]

In [92]:
#Policy evaluation
deltas = []
for i in range(numIterations):
    copygridWorld = np.copy(gridWorld)
    deltaState = []
    
    for state in states:
        weightedRewards = 0
        for action in actions:
            finalPosition, reward = actionRewardFunction(state, action)
            weightedRewards += (1/len(actions))*(reward + gamma*(gridWorld[finalPosition[0], finalPosition[1]]))
        deltaState.append(np.abs(copygridWorld[state[0], state[1]] - weightedRewards))
        copygridWorld[state[0], state[1]] = weightedRewards
    deltas.append(deltaState)        
    gridWorld = copygridWorld
            
    if i in [0, 1, 2, 9, 99, numIterations-1]:
        print("Iteration {}".format(i+1))
        print(gridWorld)
        print("")
            

Iteration 1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]

Iteration 2
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]

Iteration 3
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]

Iteration 10
[[ 0.         -6.13796997 -8.35235596 -8.96731567]
 [-6.13796997 -7.73739624 -8.42782593 -8.35235596]
 [-8.35235596 -8.42782593 -7.73739624 -6.13796997]
 [-8.96731567 -8.35235596 -6.13796997  0.        ]]

Iteration 100
[[  0.         -13.94260509 -19.91495107 -21.90482522]
 [-13.94260509 -17.92507693 -19.91551999 -19.91495107]
 [-19.91495107 -19.91551999 -17.92507693 -13.94260509]
 [-21.90482522 -19.91495107 -13.94260509   0.        ]]

Iteration 1000
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]



# Using policy iteration methods

# Rat, cheese, cat

position of rat in starting is (0,0) cat1 is (1,1) and cat2 is (2,4) and position of the cheese is (4,4).
rewards 
for cat -1.5

for cheese 5

every step -1

initial state -1

A grid world of 5*5 and in each state actions are up, down, left, right.

using random policy so probability of each action is 0.25.

apply policy iteration.

1 - policy evaluation

2 - policy improvement


# Dependencise

In [98]:
import numpy as np

# Initialize parameter

In [107]:
gamma = 1 #discount factor
rewardGoal = 5
rewardCurrent = -1.5
rewardValue = -1
gridSize = 5
terminationState1 = [[0,0]]
terminationState2 = [[1,1], [2,4]]
terminationState3 = [[gridSize-1, gridSize-1]] 
#initialState = [4,0]
actions = [[-1,0], [1,0], [0,1], [0,-1]] #up, down, right, left.
numIterations = 1000


In [117]:
def actionRewardFunction(initialState, action):
    if initialState in terminationState1:
        return initialState, -1.5
    
    
    
    if initialState in terminationState2:
        return initialState, -2.5
    
    if initialState in terminationState3:
        return initialState, 5
    
    reward = rewardValue
    finalPosition = np.array(initialState) + np.array(action)
    
    if -1 in finalPosition or 5 in finalPosition:
        finalPosition = initialPosition
        
    return finalPosition, reward
    

In [118]:
gridWorld = np.zeros((gridSize, gridSize))
states = [[i,j] for i in range(gridSize) for j in range(gridSize)]
gridWorld


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
#Policy evaluation

delta = []
for i in range(numIterations):
    copygridWorld = np.copy(gridWorld)
    deltaState = []
    for state in states:
        weightedValue = 0
        for action in actions:
            finalPosition, reward = actionRewardFunction(state, action)
            weightedValue += (1/len(actions))*(reward + gamma*(gridWorld[finalPosition[0], finalPosition[1]]))
        deltaState.append(np.abs(copygridWorld[state[0], state[1]] - weightedValue))
        copygridWorld[state[0], state[1]] = weightedValue
    delta.append(deltaState)
    gridWorld = copygridWorld
    
    if i in [0, 1, 2, 9, 99, numIterations-1]:
        print("Iteration {}".format(i+1))
        print(gridWorld)
        print("")

Iteration 1
[[-1.5 -1.  -1.  -1.  -1. ]
 [-1.  -2.5 -1.  -1.  -1. ]
 [-1.  -1.  -1.  -1.  -2.5]
 [-1.  -1.  -1.  -1.  -1. ]
 [-1.  -1.  -1.  -1.   5. ]]

Iteration 2
[[-3.    -2.625 -2.125 -2.125 -2.25 ]
 [-2.625 -5.    -2.375 -2.    -2.5  ]
 [-2.125 -2.375 -2.    -2.375 -5.   ]
 [-2.125 -2.    -2.    -2.    -1.   ]
 [-2.25  -2.125 -2.125 -0.625 10.   ]]

Iteration 3
[[-4.5     -4.28125 -3.53125 -3.34375 -3.65625]
 [-4.28125 -7.5     -3.78125 -3.34375 -4.0625 ]
 [-3.53125 -3.78125 -3.28125 -3.75    -7.5    ]
 [-3.34375 -3.15625 -3.03125 -2.5     -1.     ]
 [-3.5625  -3.34375 -2.9375  -0.28125 15.     ]]

Iteration 10
[[-1.50000000e+01 -1.66455097e+01 -1.47559910e+01 -1.40675640e+01
  -1.45156422e+01]
 [-1.65937004e+01 -2.50000000e+01 -1.60497665e+01 -1.44545593e+01
  -1.64220543e+01]
 [-1.44929543e+01 -1.55455990e+01 -1.33647327e+01 -1.40742321e+01
  -2.50000000e+01]
 [-1.33275814e+01 -1.23315506e+01 -9.92645645e+00 -5.63558960e+00
  -4.49752808e-02]
 [-1.34057350e+01 -1.20384636e+01 -